// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDaTsd1naqlxuvYukZggpfE7szRbqpcQk',
    appId: '1:285982006243:web:e37581470d60f363045ed6',
    messagingSenderId: '285982006243',
    projectId: 'to-do-practice-bb05e',
    authDomain: 'to-do-practice-bb05e.firebaseapp.com',
    storageBucket: 'to-do-practice-bb05e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Qb03qkroEwE82pcFZiA0mGKwwGhNZiI',
    appId: '1:285982006243:android:6300f34739a29c60045ed6',
    messagingSenderId: '285982006243',
    projectId: 'to-do-practice-bb05e',
    storageBucket: 'to-do-practice-bb05e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxcp6nw_YMvIuUIJ7uHKjCilulG5iAY4I',
    appId: '1:285982006243:ios:e33db2de2bd18e13045ed6',
    messagingSenderId: '285982006243',
    projectId: 'to-do-practice-bb05e',
    storageBucket: 'to-do-practice-bb05e.appspot.com',
    iosBundleId: 'com.example.toDoPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxcp6nw_YMvIuUIJ7uHKjCilulG5iAY4I',
    appId: '1:285982006243:ios:e33db2de2bd18e13045ed6',
    messagingSenderId: '285982006243',
    projectId: 'to-do-practice-bb05e',
    storageBucket: 'to-do-practice-bb05e.appspot.com',
    iosBundleId: 'com.example.toDoPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDaTsd1naqlxuvYukZggpfE7szRbqpcQk',
    appId: '1:285982006243:web:c7d2c3bb1be16008045ed6',
    messagingSenderId: '285982006243',
    projectId: 'to-do-practice-bb05e',
    authDomain: 'to-do-practice-bb05e.firebaseapp.com',
    storageBucket: 'to-do-practice-bb05e.appspot.com',
  );
}
