// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARkoO-BzKsDonbRXjwi8r7dMxyW9N2XEA',
    appId: '1:1069514788756:web:e32f095fce8007fad00981',
    messagingSenderId: '1069514788756',
    projectId: 'to-do-a37fc',
    authDomain: 'to-do-a37fc.firebaseapp.com',
    storageBucket: 'to-do-a37fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD-d5cX482vzeP-Tfj6ioB9O6WViPHRBc',
    appId: '1:1069514788756:android:f123eec0ced922bdd00981',
    messagingSenderId: '1069514788756',
    projectId: 'to-do-a37fc',
    storageBucket: 'to-do-a37fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADlSLuxFJ8ywNClN-_1ZaNaYQWwK5RI7I',
    appId: '1:1069514788756:ios:d3b78448ce3577d1d00981',
    messagingSenderId: '1069514788756',
    projectId: 'to-do-a37fc',
    storageBucket: 'to-do-a37fc.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADlSLuxFJ8ywNClN-_1ZaNaYQWwK5RI7I',
    appId: '1:1069514788756:ios:d3b78448ce3577d1d00981',
    messagingSenderId: '1069514788756',
    projectId: 'to-do-a37fc',
    storageBucket: 'to-do-a37fc.appspot.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARkoO-BzKsDonbRXjwi8r7dMxyW9N2XEA',
    appId: '1:1069514788756:web:ccf01eb752341841d00981',
    messagingSenderId: '1069514788756',
    projectId: 'to-do-a37fc',
    authDomain: 'to-do-a37fc.firebaseapp.com',
    storageBucket: 'to-do-a37fc.appspot.com',
  );
}
